name: Run tests

on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npm test
