schema {
  query: RootQuery
  mutation: RootMutation
  subscription: RootSubscription
}

type Post {
  content: String!
}

type RootQuery {
  posts: [Post!]!
}

type RootMutation {
  appendPost(post: Post!): Post!
}

type RootSubscription {
  newPost: Post!
}
