type FamilyInfo {
  id: ID!
  father: User!
  mother: User!
  brothers: [User]!
  isLocal: Boolean!
}

type Query {
  getFamilyInfo: FamilyInfo
  getFamilyInfoByIsLocal(isLocal: Boolean!): FamilyInfo
}
