scalar JSON

type User {
  email: String!
  username: String!
  fullName: String!
}

type Me {
  id: ID!
  email: String!
  username: String!
  fullName: String!
  addresses: [String]!
  scores: [Int]!
  age: Int
  phone: [String]!
  apiKey: String! # This is going to be the id of the user on the front-end
  familyInfo: [FamilyInfo]!
}

type FamilyInfo {
  father: User!
  mother: User!
  brothers: [User]!
}

# MUTATIONS

# Create a new User
input UserInput {
  email: String!
  username: String!
  fullName: String!
  password: String!
}
# Login
input LoginInput {
  email: String!
  password: String!
}
# Update password
input UpdatePasswordInput {
  oldPassword: String!
  newPassword: String!
}

type Query {
  getMe: Me
  getUserByUsername(username: String!, name: String!): User
}

type Mutation {
  createUser(input: UserInput!): User
  login(input: LoginInput!): Me
  updatePassword(input: UpdatePasswordInput!): Me
}
